[gcp_service_account]
type = "service_account"
project_id = "projeto-trafego-waze"
private_key_id = "ef05087409d01e750756fee41b7449dbad09477e"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDMUF2/BGzdiJQX
0bNCM00xeC6E/BeNyV1yPYOfG6/5hrfOC6oolk/njB4qK3L+l9MikjEZxs+VCdkW
R3sQUZSF2b2TPVUljef7cHebOdHTB0ZQa3YRT59JwFxja2SOaNfE8Ixeb6LJKVr6
+31ugI1RFwoDKMVYVk4njuVlg/9HZLZZIgyPT0zhwYcS5o313W2tU9ssP5bIA6SJ
4DJiMHcoo1n1141UBd6b0ubFGo7op57FMtGncwn5YUQsEo5Qo+ASLZP6SZkDCJya
e1K0ivgfM/F4QXAycB9WckP/tZsqvyQeeUYEZfT00Movqcvh+g8HdzZx7AcZ5a/H
AMK5jVKlAgMBAAECggEAHBzEwWdA+Xx08BAVC7tWWEOylu6+6O33kyP+q9JZ9MoC
GXJGb/46sV/4uJGw6XIHhZ667dKKtnWb7rJYLwcimgY7TPqn8Bpl/JVdh7i9c71x
Adi/bqNXhgTXUYCx3dx0L+9vSQEwU2CC2bzn5d//UdSLNqMSAFUjvNKvIrg2VGK6
f/4mNKKqO68KSPhU2XN1gUdAcc0G5Ag4Ia2+1yELXaeeD97ZaM22bXMvonTuVjjM
qYEITyU2EBfEoLkivuLqf8AaphJJiQ5/7QaAz084SeZqoFSwne45Aeq7ynZq8GJN
dReQQQuHTIM36MKvoWsmvUrKQNDfes7Tnu0bUgCycwKBgQD5DaUd80IzMU5uHyOr
m3OA28s3Mlzoz14cLw15vaq64Ll4kr8O79vPfYSj3odGDKlOOLYvXV8ja4lv7Zs3
sCXSrkEB+q1aV1lAONihK0qG4CFILuor434qbVgoJ+q6Y3P/UXTBY0E1id2qQ/iq
gqCmyPU33VVBGllAp04+9nU2iwKBgQDSA0L0olt1WSUZUiqYYII6PlBlJjOuzpz7
mpMdV8Z90aT83kPSa0laBM8W3Wr975BdzEWe8tZGnVkxTd/BQZxnVkBy/hCfnDKa
1kZVcl6A+Hoq7uI/c01X6gDr7jbNc3epn3dti8IoBEswukq7w67athF471/KDYHj
thU3k5HxjwKBgGKUsRfy0vBagvX542+o34ZQ+dZGXBpXAqRbR5U5qxu/mgqM441x
CevOfjMzAQ6MMnPg5NRIvEDT7xnbzkWztrT2/opfBEEvNAfEuJLLBPvwOZxN3akz
qhv3Hh7+9d2DQkX8ox9tP0GG6bPcpdAwVpDOGKpdNMLJQCzkTIeFnI3TAoGBAL2j
elODREj73Xc27gW4p//GAzzDOUoxginkk9GcUD2PEIfSgLXCcXMbApFoEVQKfndk
nL2CFKGhNkhCRLmy8HOTvBDagNJP7pZIxSwlYVbeiRq5qY2YJZAsWvawncX57WU6
/VHrMMCH2AnBPvi8I+mVHMPyi7Hdbpvb8N7Fn7TbAoGBAMT4F4qNsjG+DNC4RPYp
klH8T2JawJWS6iNT8CiXjd+Z01Ok7Fez/m7WBFCsjWv4TJHYVCC4Dr//MP+Erfym
5tjeSd4jl1f3cqo0qCzSRWAhzm/DeGA49YQQA5bmReZ5wYsfmeGAN2Oh386gAZhz
nRZHHb1vtXYerU4vIKo2XqYX
-----END PRIVATE KEY-----
"""
client_email = "trafego-foz-do-igua-u@projeto-trafego-waze.iam.gserviceaccount.com"
client_id = "103273267171906432789"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/trafego-foz-do-igua-u%40projeto-trafego-waze.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
